### PR TITLE
Fix Attributes get deleted when applying Range to Attribute Node

### PR DESCRIPTION
**Pull request by DasLixou**

### CODE REVIEW

**Comment by DasLixou** [comment]
This overrides the WithRange method in StdSimpleCallNodeWithAttrs so that the StdComplexCallNode is a StdComplexCallNodeWithAttrs with their attributes.

**Comment by qwertie** [comment]
Hi! Thanks for this, but due to technical difficulties, this repository has been dormant for the last five years.

All work is now done in the monorepo [here](https://github.com/qwertie/ecsharp). It does appear that the bug you identified is still present in that repo!

If one of the Loyc web sites directed you to this repo, let me know which page so I can update it.

**Comment by qwertie** [comment]
I've now pushed a fix for this bug to [the main repo](https://github.com/qwertie/ecsharp) and also published it to NuGet as v30.1.0.

**Comment by DasLixou** [comment]
Thanks for the response! I just googled Loyc Github and hoped to find a repo :D But i wanna say that this repo is still linked at the bottom left at http://core.loyc.net/ -  nice to know that the code is still getting updates 👍

**Pull request closed without merging**
